version: "3.9"

services:
  redis-server:
    hostname: redis
    container_name: REDIS-SERVER
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

#  postgres:
#    container_name: POSTGRES
#    image: postgres:9.4
#    environment:
#      - POSTGRES_USER=app_user
#      - POSTGRES_PASSWORD=app_password
#      - POSTGRES_DB=app_db
#    ports:
#      - "5432:5432"

  mysql:
    container_name: MYSQL
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=pa_task_management
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3366:3306"
    expose:
      - 3366
    volumes:
      - db_data:/var/lib/mysql
      - ./deployment/db/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql

  service-registry:
    container_name: SERVICE-REGISTRY
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  hystrix-dashboard:
    container_name: HYSTRIX-DASHBOARD
    build:
      context: ./hystrix-dashboard
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://SERVICE-REGISTRY:8761/eureka/
    depends_on:
      - service-registry
    ports:
      - "9295:9295"

  cloud-config-server:
    container_name: CLOUD-CONFIG-SERVER
    build:
      context: ./cloud-config-server
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://SERVICE-REGISTRY:8761/eureka/
    depends_on:
      - service-registry
    ports:
      - "9296:9296"

  cloud-gateway:
    container_name: CLOUD-GATEWAY
    build:
      context: ./cloud-gateway
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://SERVICE-REGISTRY:8761/eureka/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    depends_on:
      - service-registry
      - cloud-config-server
      - redis-server
    ports:
      - "8080:5005"
    expose:
      - 8080
    links:
      - "redis-server:redis"

  auth-server:
    container_name: AUTH-SERVER
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://SERVICE-REGISTRY:8761/eureka/
      - DB_URL=mysql
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    depends_on:
      - service-registry
      - redis-server
      - mysql
    ports:
      - "6650:5005"
    links:
      - "redis-server:redis"

  core-service:
    container_name: CORE_SERVICE
    build:
      context: ./core-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://SERVICE-REGISTRY:8761/eureka/
      - DB_URL=mysql
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    depends_on:
      - service-registry
      - redis-server
      - mysql
    ports:
      - "6651:5005"


volumes:
  db_data:
    driver: local

networks:
  default:
    name: micro-network
    external: true